### ISSUE TITLE
New icons are not used

### ISSUE THREAD

**Issue by jstashh** [yearn/yearn-api#25]
**Steps to reproduce**
* Run the api
* A new vault is endorsed, an icon is added to https://github.com/yearn/yearn-assets e.g. in this PR https://github.com/yearn/yearn-assets/pull/174
* Go to localhost:3000/v1/chains/250/vaults/get
* Data for the new vault is present but the `displayIcon` field is `""`
* No icon is displayed on the website

This is because icons are loaded at initialization of the sdk, and not updated thereafter

**To fix**
Find someway to recognize when a vault has been added and refresh the data from the assets service (https://github.com/yearn/yearn-sdk/blob/master/src/services/assets.ts). Perhaps this could be a scheduled job

**Comment by piiih** [comment]
@jstashh Do you know how can I create a new vault and endorese it to test?

**Comment by psparacino** [comment]
I was going to leave same question as above; what's the method to create a new vault to test?  Right now the field is populated following the steps

**Comment by jstashh** [comment]
@piiih @psparacino thanks for taking a look at this. To test this I'd probably run a mainnet fork with brownie/ganache and then point a locally running api to localhost:8545. Then I'd use the brownie console to endorse a new vault on the registry (https://etherscan.io/address/0x50c1a2ea0a861a967d9d0ffe2ae4012c2e053804#writeContract), or alternatively just make a new vault

**Comment by jstashh** [comment]
@piiih @psparacino if you have any more questions please feel free to reach out on discord
