### ISSUE TITLE
Capture any errors and exceptions with Sentry

### ISSUE THREAD

**Issue by numan** [yearn/yearn-api#32]
## Background

[Sentry](https://sentry.io/welcome/) is an error tracking platform. It can be used to collect, track and diagnose unexpected errors.

All critical services should have sentry integration.

## Goal

1. Capture all fastify errors with Sentry
2. Capture all errors in [bree](https://github.com/breejs/bree) jobs with Sentry

**Comment by phillip055** [comment]
Hey, do you mind if i pick this up?

**Comment by numan** [comment]
> Hey, do you mind if i pick this up?

Hey, I think someone else on telegram has already claimed it. I'm sure we can find some way for you to contribute.

Please hop into the infrastructure channel on discord if you're interested in contributing:

https://discord.gg/7GDKSf5x

**Comment by malawadd** [comment]
> Hey, do you mind if i pick this up?

yeah im the only who claimed this , im currently going through Sentry docs to familiarize myself with it , but if you're up to it go ahead , it might take me awhile and im not sure how urgent is this.

**Comment by numan** [comment]
@phillip055 all yours if you still want it

**Comment by phillip055** [comment]
Hey, @malawadd you should give it a go 👊, if not I will hop back in a day or two.

**Comment by phillip055** [comment]
Picking this up
